# Angular dev container
FROM node:20-alpine

WORKDIR /usr/src/app

ENV CI=true

COPY package*.json .npmrc ./
RUN npm install --legacy-peer-deps

COPY . .

EXPOSE 4200

# Bind to 0.0.0.0 so it's reachable from host
CMD ["npx","ng","serve","--host","0.0.0.0","--port","4200"]
